"""add forecast log, observer, context_signal

Revision ID: 5d7172ef8a00
Revises: 90c13b12f8e4
Create Date: 2026-09-10 10:59:01.021546

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import vervana.db.base  # custom column types (e.g. UTCDateTime) referenced in migrations

# revision identifiers, used by Alembic.
revision: str = "5d7172ef8a00"
down_revision: str | Sequence[str] | None = "90c13b12f8e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "context_signal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_type", sa.String(length=40), nullable=False),
        sa.Column("region", sa.String(length=80), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("value_numeric", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("value_text", sa.String(length=200), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "observer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=80), nullable=False),
        sa.Column("trades_in_reported_commodities", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prospective_forecast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commodity_id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("made_at", vervana.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("model", sa.String(length=40), nullable=False),
        sa.Column("point_paise", sa.BigInteger(), nullable=False),
        sa.Column("low_paise", sa.BigInteger(), nullable=False),
        sa.Column("high_paise", sa.BigInteger(), nullable=False),
        sa.Column("actual_paise", sa.BigInteger(), nullable=True),
        sa.Column("abs_error_paise", sa.BigInteger(), nullable=True),
        sa.Column("hit_interval", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["commodity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["market.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prospective_forecast")
    op.drop_table("observer")
    op.drop_table("context_signal")
    # ### end Alembic commands ###
