"""add retail_offer_detail

Revision ID: 90c13b12f8e4
Revises: e53f98c2c2b2
Create Date: 2026-09-10 10:43:31.097832

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90c13b12f8e4"
down_revision: str | Sequence[str] | None = "e53f98c2c2b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retail_offer_detail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("sku_title", sa.String(length=300), nullable=False),
        sa.Column("pack_size_raw", sa.String(length=64), nullable=False),
        sa.Column("pack_kg", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("mrp_paise", sa.BigInteger(), nullable=True),
        sa.Column("selling_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("fees_paise", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["price_observation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("retail_offer_detail")
    # ### end Alembic commands ###
