"""add invoice

Revision ID: 9b31808e6ada
Revises: 5d7172ef8a00
Create Date: 2026-09-10 11:39:38.539601

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b31808e6ada"
down_revision: str | Sequence[str] | None = "5d7172ef8a00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commodity_id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("price_paise_per_kg", sa.BigInteger(), nullable=False),
        sa.Column("trader", sa.String(length=160), nullable=True),
        sa.Column("source_ref", sa.String(length=300), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["commodity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["market.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invoice")
    # ### end Alembic commands ###
