"""initial schema

Revision ID: cd20efe19344
Revises:
Create Date: 2026-09-10 08:07:19.798148

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import vervana.db.base  # custom column types (e.g. UTCDateTime) referenced in migrations

# revision identifiers, used by Alembic.
revision: str = "cd20efe19344"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias_text", sa.String(length=200), nullable=False),
        sa.Column("alias_language", sa.String(length=16), nullable=False),
        sa.Column(
            "alias_source_type",
            sa.Enum(
                "agmarknet_official",
                "hindi_spoken",
                "hinglish_transliteration",
                "qcomm_sku_title",
                "trader_colloquial",
                name="aliassourcetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "canonical_type",
            sa.Enum(
                "commodity", "variety", "grade", "market", name="canonicaltype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("canonical_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("created_by", sa.String(length=80), nullable=False),
        sa.Column("verified_by", sa.String(length=80), nullable=True),
        sa.Column("verified_at", vervana.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alias", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alias_canonical", ["canonical_type", "canonical_id"], unique=False
        )
        batch_op.create_index("ix_alias_text", ["alias_text"], unique=False)

    op.create_table(
        "commodity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=120), nullable=False),
        sa.Column("agmarknet_commodity_code", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_name"),
    )
    op.create_table(
        "market",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=160), nullable=False),
        sa.Column("apmc_name", sa.String(length=160), nullable=True),
        sa.Column("city", sa.String(length=80), nullable=True),
        sa.Column("state", sa.String(length=80), nullable=True),
        sa.Column("agmarknet_market_code", sa.String(length=32), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_name"),
    )
    op.create_table(
        "alias_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="reviewstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("proposed_by", sa.String(length=80), nullable=False),
        sa.Column("proposed_at", vervana.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=True),
        sa.Column("score", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("decided_by", sa.String(length=80), nullable=True),
        sa.Column("decided_at", vervana.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["alias_id"],
            ["alias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grade",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commodity_id", sa.Integer(), nullable=True),
        sa.Column("canonical_name", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["commodity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "unit_convention",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=True),
        sa.Column("commodity_id", sa.Integer(), nullable=True),
        sa.Column("unit_raw", sa.String(length=64), nullable=False),
        sa.Column("kg_equivalent", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["commodity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["market.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("unit_convention", schema=None) as batch_op:
        batch_op.create_index(
            "ix_unitconv_lookup", ["commodity_id", "market_id", "unit_raw"], unique=False
        )

    op.create_table(
        "variety",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commodity_id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=120), nullable=False),
        sa.Column("agmarknet_variety_code", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["commodity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("variety", schema=None) as batch_op:
        batch_op.create_index("ix_variety_commodity", ["commodity_id"], unique=False)

    op.create_table(
        "price_observation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commodity_id", sa.Integer(), nullable=False),
        sa.Column("variety_id", sa.Integer(), nullable=True),
        sa.Column("grade_id", sa.Integer(), nullable=True),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column(
            "source_class",
            sa.Enum(
                "quote_indicative",
                "executed_summary",
                "executed_trade",
                "retail_offer",
                name="sourceclass",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("price_low_paise", sa.BigInteger(), nullable=False),
        sa.Column("price_high_paise", sa.BigInteger(), nullable=False),
        sa.Column("price_point_paise", sa.BigInteger(), nullable=True),
        sa.Column("unit_raw", sa.String(length=64), nullable=False),
        sa.Column("canonical_price_paise_per_kg", sa.BigInteger(), nullable=True),
        sa.Column("unit_kg_equivalent", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("unit_conversion_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("raw_quote", sa.Text(), nullable=False),
        sa.Column("observed_at", vervana.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "time_basis",
            sa.Enum(
                "exact",
                "estimated_window",
                "single_daily_quote",
                "daily_summary",
                name="timebasis",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "observed_window_start", vervana.db.base.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("observed_window_end", vervana.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("observer_id", sa.Integer(), nullable=True),
        sa.Column("supersedes_id", sa.Integer(), nullable=True),
        sa.Column("supersede_reason", sa.Text(), nullable=True),
        sa.Column("created_at", vervana.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(trim(raw_quote)) > 0", name="ck_raw_quote_present"),
        sa.CheckConstraint("length(trim(source_url)) > 0", name="ck_source_url_present"),
        sa.CheckConstraint("price_low_paise <= price_high_paise", name="ck_price_range_ordered"),
        sa.CheckConstraint(
            "price_point_paise IS NULL OR (price_point_paise >= price_low_paise AND price_point_paise <= price_high_paise)",
            name="ck_point_within_range",
        ),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["commodity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["grade.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["market.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["price_observation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variety_id"],
            ["variety.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("price_observation", schema=None) as batch_op:
        batch_op.create_index(
            "ix_obs_commodity_time", ["commodity_id", "observed_at"], unique=False
        )
        batch_op.create_index("ix_obs_market_time", ["market_id", "observed_at"], unique=False)
        batch_op.create_index("ix_obs_source_class", ["source_class"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_observation", schema=None) as batch_op:
        batch_op.drop_index("ix_obs_source_class")
        batch_op.drop_index("ix_obs_market_time")
        batch_op.drop_index("ix_obs_commodity_time")

    op.drop_table("price_observation")
    with op.batch_alter_table("variety", schema=None) as batch_op:
        batch_op.drop_index("ix_variety_commodity")

    op.drop_table("variety")
    with op.batch_alter_table("unit_convention", schema=None) as batch_op:
        batch_op.drop_index("ix_unitconv_lookup")

    op.drop_table("unit_convention")
    op.drop_table("grade")
    op.drop_table("alias_review")
    op.drop_table("market")
    op.drop_table("commodity")
    with op.batch_alter_table("alias", schema=None) as batch_op:
        batch_op.drop_index("ix_alias_text")
        batch_op.drop_index("ix_alias_canonical")

    op.drop_table("alias")
    # ### end Alembic commands ###
