"""add ingest_run

Revision ID: e53f98c2c2b2
Revises: cd20efe19344
Create Date: 2026-09-10 08:54:48.533574

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import vervana.db.base  # custom column types (e.g. UTCDateTime) referenced in migrations

# revision identifiers, used by Alembic.
revision: str = "e53f98c2c2b2"
down_revision: str | Sequence[str] | None = "cd20efe19344"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connector", sa.String(length=40), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", vervana.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", vervana.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("rows_in", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("rejection_reasons", sa.JSON(), nullable=True),
        sa.Column("raw_payload_path", sa.String(length=500), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingest_run")
    # ### end Alembic commands ###
